/* SPDX-License-Identifier: BUSL-1.1 */
#ifndef LISA_GUI_H
#define LISA_GUI_H
/*
 * `lisa gui`: the web UI in gui/ is compiled into the binary
 * (lisa_gui_assets, generated by cmake/embed_assets.cmake) and served by
 * the local HTTP server; gui_show opens it in a native window (webview,
 * macOS) or, where that is unavailable, in the default browser.
 */

#include "../http/server.h"

extern const server_asset_t lisa_gui_assets[];
extern const int lisa_gui_asset_count;

/* 1 if this build can show a native window. */
int gui_native_available(void);

/*
 * Show url (with the session token in its fragment) in a native window
 * and return when the window is closed or a stop signal arrives. Must be
 * called on the main thread.
 */
int gui_show_window(const char* url);

#endif /* LISA_GUI_H */
