# SPDX-License-Identifier: BUSL-1.1
# Embed a Tesseract traineddata file into a C source, so OCR needs no files
# on disk (single-executable rule). Run as:
#   cmake -DOUT=<file.c> -DSRC=<eng.traineddata> -P embed_tessdata.cmake

file(READ "${SRC}" hex HEX)
string(LENGTH "${hex}" hexlen)
math(EXPR len "${hexlen} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
string(REGEX REPLACE "((0x..,){16})" "\\1\n    " bytes "${bytes}")

set(body "/* Generated by cmake/embed_tessdata.cmake. Do not edit. */\n")
string(APPEND body "const unsigned char lisa_tessdata_eng[${len}] = {\n    ${bytes}\n};\n")
string(APPEND body "const unsigned long lisa_tessdata_eng_len = ${len};\n")

# Write only when changed, so unchanged builds do not recompile.
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL body)
    file(WRITE "${OUT}" "${body}")
endif()
