# SPDX-License-Identifier: BUSL-1.1
# Turn the GUI's files into a C source (a server_asset_t table), so they are
# compiled into the lisa binary. Run as:
#   cmake -DOUT=<file.c> -DSRC=<gui dir> -P embed_assets.cmake
# Only the files listed here are embedded; each gets its MIME type.

# file|url|type (all text files are served as UTF-8)
set(ASSETS
    "index.html|/index.html|text/html"
    "app.css|/app.css|text/css"
    "app.js|/app.js|text/javascript"
)

set(body "/* Generated by cmake/embed_assets.cmake from gui/. Do not edit. */\n")
string(APPEND body "#include \"http/server.h\"\n\n")
set(table "")
set(i 0)
foreach(entry IN LISTS ASSETS)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 file)
    list(GET parts 1 url)
    list(GET parts 2 mime)
    file(READ "${SRC}/${file}" hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR len "${hexlen} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x..,){16})" "\\1\n    " bytes "${bytes}")
    string(APPEND body "static const unsigned char asset_${i}[${len}] = {\n    ${bytes}\n};\n\n")
    string(APPEND table "    { \"${url}\", \"${mime}; charset=utf-8\", asset_${i}, ${len} },\n")
    math(EXPR i "${i} + 1")
endforeach()
string(APPEND body "const server_asset_t lisa_gui_assets[] = {\n${table}};\n")
string(APPEND body "const int lisa_gui_asset_count = ${i};\n")

# Write only when changed, so unchanged builds do not recompile.
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL body)
    file(WRITE "${OUT}" "${body}")
endif()
