/* SPDX-License-Identifier: BUSL-1.1 */
/*
 * platform_ocr_tesseract.c — OCR backend for Linux and Windows, where there
 * is no system recogniser (macOS uses Apple Vision in platform_macos.m).
 *
 * Tesseract (LSTM engine) over Leptonica, both built in-tree and statically
 * linked. The English model (eng.traineddata) is embedded in the binary
 * (cmake/embed_tessdata.cmake) and extracted once to the per-user data dir,
 * so the executable stays self-contained.
 *
 * The caller (src/documents/pdf.c) passes a rasterised page as 32-bit BGRx
 * rows. We wrap it in a Leptonica PIX and hand it to Tesseract, returning
 * one recognised line per text line, exactly like the Vision backend.
 */

#include "platform.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <allheaders.h>        /* Leptonica */
#include <tesseract/capi.h>    /* Tesseract C API */

/* Embedded eng.traineddata (generated by cmake/embed_tessdata.cmake). */
extern const unsigned char lisa_tessdata_eng[];
extern const unsigned long lisa_tessdata_eng_len;

static lisa_mutex_t* g_lock;          /* serialises the shared API below */
static TessBaseAPI*  g_api;           /* cached across calls once ready */
static int           g_init_failed;   /* 1 after a permanent init failure */
static char*         g_datadir;       /* parent dir of tessdata/ */

/* Write the embedded model to <data>/tessdata/eng.traineddata if absent.
 * Returns a malloc'd parent path (the Tesseract datapath), or NULL. */
static char* ensure_traineddata(void) {
    char* base = lisa_default_data_dir();
    if (base == NULL) return NULL;
    char* tessdir = lisa_path_join(base, "tessdata");
    free(base);
    if (tessdir == NULL) return NULL;
    if (lisa_mkdirs(tessdir) != LISA_PLAT_OK) { free(tessdir); return NULL; }

    char* file = lisa_path_join(tessdir, "eng.traineddata");
    if (file == NULL) { free(tessdir); return NULL; }

    int ok = 1;
    if (!lisa_path_exists(file)) {
        FILE* f = fopen(file, "wb");
        if (f == NULL) {
            ok = 0;
        } else {
            size_t n = fwrite(lisa_tessdata_eng, 1, (size_t)lisa_tessdata_eng_len, f);
            if (fclose(f) != 0 || n != (size_t)lisa_tessdata_eng_len) {
                lisa_remove_file(file);   /* don't leave a truncated model */
                ok = 0;
            }
        }
    }
    free(file);
    free(tessdir);
    if (!ok) return NULL;

    /* Tesseract's datapath is the parent of the tessdata/ directory, i.e.
     * the per-user data dir we just wrote tessdata/eng.traineddata into. */
    return lisa_default_data_dir();
}

/* Lazily create and initialise the shared Tesseract API. Caller holds g_lock. */
static TessBaseAPI* get_api(void) {
    if (g_api != NULL) return g_api;
    if (g_init_failed) return NULL;

    if (g_datadir == NULL) g_datadir = ensure_traineddata();
    if (g_datadir == NULL) { g_init_failed = 1; return NULL; }

    TessBaseAPI* api = TessBaseAPICreate();
    if (api == NULL) { g_init_failed = 1; return NULL; }
    /* OEM_LSTM_ONLY (1): the vendored build has the legacy engine disabled. */
    if (TessBaseAPIInit2(api, g_datadir, "eng", OEM_LSTM_ONLY) != 0) {
        TessBaseAPIDelete(api);
        g_init_failed = 1;
        return NULL;
    }
    g_api = api;
    return g_api;
}

int lisa_ocr_available(void) {
    return 1;
}

/* Build a Leptonica 32-bpp PIX from the caller's BGRx rows. */
static PIX* pix_from_bgrx(const unsigned char* pixels, int width, int height, int stride) {
    PIX* pix = pixCreate(width, height, 32);
    if (pix == NULL) return NULL;
    pixSetResolution(pix, 300, 300);   /* helps the recogniser's sizing */
    l_uint32* data = pixGetData(pix);
    int wpl = pixGetWpl(pix);
    for (int y = 0; y < height; y++) {
        const unsigned char* row = pixels + (size_t)y * (size_t)stride;
        l_uint32* line = data + (size_t)y * (size_t)wpl;
        for (int x = 0; x < width; x++) {
            const unsigned char* p = row + (size_t)x * 4;  /* B, G, R, x */
            composeRGBPixel(p[2], p[1], p[0], &line[x]);
        }
    }
    return pix;
}

int lisa_ocr_image(const unsigned char* pixels, int width, int height, int stride, char** out) {
    if (out) *out = NULL;
    if (pixels == NULL || out == NULL || width <= 0 || height <= 0 || stride < width * 4)
        return LISA_PLAT_EINVAL;

    if (g_lock == NULL) {
        /* First use: create the lock. A benign race only leaks one mutex. */
        lisa_mutex_t* m = NULL;
        if (lisa_mutex_create(&m) != LISA_PLAT_OK || m == NULL) return LISA_PLAT_ENOMEM;
        g_lock = m;
    }

    lisa_mutex_lock(g_lock);
    TessBaseAPI* api = get_api();
    if (api == NULL) { lisa_mutex_unlock(g_lock); return LISA_PLAT_EIO; }

    PIX* pix = pix_from_bgrx(pixels, width, height, stride);
    if (pix == NULL) { lisa_mutex_unlock(g_lock); return LISA_PLAT_ENOMEM; }

    TessBaseAPISetImage2(api, pix);
    char* text = TessBaseAPIGetUTF8Text(api);   /* may be NULL */
    TessBaseAPIClear(api);
    pixDestroy(&pix);

    int rc;
    if (text == NULL) {
        *out = NULL;
        rc = LISA_PLAT_OK;     /* nothing recognised is not an error */
    } else {
        *out = strdup(text);
        TessDeleteText(text);
        rc = *out ? LISA_PLAT_OK : LISA_PLAT_ENOMEM;
    }
    lisa_mutex_unlock(g_lock);
    return rc;
}
